import React from 'react';

export default function PlaceHolderLongText(props) {
    return(
        <p style={{backgroundSize: 'cover',}} {...props}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed efficitur massa, quis semper nunc. Cras elementum ante sed feugiat pellentesque. Vestibulum ut lacus malesuada, malesuada odio nec, dictum nunc. Duis hendrerit lacus vitae mauris consequat tempus. Aliquam consectetur semper neque, sit amet pulvinar elit interdum quis. Ut elementum placerat ex, sit amet tristique risus elementum quis. In facilisis augue in scelerisque facilisis. Maecenas sed ullamcorper ex, non laoreet enim. Aenean eu erat accumsan, dapibus mi in, suscipit erat. Nulla tempus nisi sit amet odio vestibulum, at auctor ligula rhoncus. Curabitur quis sapien sit amet libero semper suscipit in a ligula. Praesent vel ex eu turpis fermentum placerat sit amet sit amet turpis. Quisque egestas, quam in hendrerit consectetur, sem lectus mattis diam, iaculis semper tellus ex quis ligula.

Cras sollicitudin, enim nec sollicitudin hendrerit, libero lorem finibus nibh, id rhoncus risus ex ut arcu. Vestibulum eget ultricies tellus. Suspendisse ut porttitor erat. Sed at nulla sit amet odio facilisis faucibus in id ante. Vestibulum at molestie arcu, sed suscipit nulla. Fusce cursus cursus felis, quis facilisis justo efficitur vitae. Cras nec velit ligula. Maecenas enim enim, vehicula quis ipsum vitae, molestie laoreet ligula. Mauris aliquam diam orci, a volutpat libero vestibulum ac. Praesent congue vehicula nunc, sit amet eleifend felis lacinia ac. Mauris interdum suscipit ligula, a facilisis neque mattis sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur blandit leo eget egestas aliquam. Cras ut arcu elit. Vivamus in erat eu sem dapibus ultricies.

Sed urna sem, maximus faucibus malesuada non, lacinia eu libero. Mauris placerat sollicitudin ullamcorper. Nam auctor tristique justo eu commodo. Morbi eu dui ultrices, lacinia felis lacinia, sollicitudin orci. Phasellus quam odio, scelerisque id pharetra ut, lacinia eu nisl. Nulla interdum quam odio, vel ultrices leo laoreet sit amet. Morbi quis felis at neque congue facilisis. Praesent varius tellus vitae scelerisque fermentum. Sed commodo risus non neque commodo dapibus. Mauris fermentum efficitur orci vel facilisis.

In convallis, arcu vel tincidunt rhoncus, urna orci interdum mauris, sed vehicula ipsum dolor ut mi. Suspendisse sit amet turpis sit amet tortor aliquet congue a ac massa. Maecenas nec nisi enim. Suspendisse pulvinar faucibus lacus, a suscipit mauris sodales eu. Phasellus vulputate dolor dolor, vel convallis ipsum accumsan vitae. Quisque sodales condimentum dolor. Cras porttitor elit vitae ligula mattis, ac tincidunt metus venenatis. Vivamus at posuere tortor. Fusce tempor nunc risus, at tincidunt metus accumsan sit amet. Nulla commodo vulputate diam in placerat. Ut accumsan mi ipsum, vel tempor dui mattis eu. Nulla facilisi.

Vivamus dignissim varius tellus, non euismod metus varius id. Integer dolor neque, dignissim et ligula nec, lobortis congue lorem. Quisque rutrum, mauris at lacinia elementum, neque sapien aliquet turpis, nec euismod odio libero a justo. Phasellus ac dolor augue. In consequat nunc mauris, at auctor lorem sodales eget. Proin quis ipsum nibh. Maecenas a est et nisi facilisis consequat. Quisque porta, tellus et bibendum pharetra, nisi felis venenatis nibh, a blandit ex mi sed nibh. In ultrices risus enim, at maximus eros tincidunt quis. Donec molestie, tellus at faucibus interdum, felis leo hendrerit leo, vitae accumsan lorem augue sed leo. Nunc luctus mi urna, id interdum eros sodales sit amet. Duis purus orci, dictum vel urna at, aliquet maximus tellus. Vestibulum porttitor, tellus eget posuere congue, tellus nibh viverra dui, quis efficitur tortor nisi vestibulum est. Nam vel dui laoreet urna suscipit faucibus a sit amet urna.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed efficitur massa, quis semper nunc. Cras elementum ante sed feugiat pellentesque. Vestibulum ut lacus malesuada, malesuada odio nec, dictum nunc. Duis hendrerit lacus vitae mauris consequat tempus. Aliquam consectetur semper neque, sit amet pulvinar elit interdum quis. Ut elementum placerat ex, sit amet tristique risus elementum quis. In facilisis augue in scelerisque facilisis. Maecenas sed ullamcorper ex, non laoreet enim. Aenean eu erat accumsan, dapibus mi in, suscipit erat. Nulla tempus nisi sit amet odio vestibulum, at auctor ligula rhoncus. Curabitur quis sapien sit amet libero semper suscipit in a ligula. Praesent vel ex eu turpis fermentum placerat sit amet sit amet turpis. Quisque egestas, quam in hendrerit consectetur, sem lectus mattis diam, iaculis semper tellus ex quis ligula.

Cras sollicitudin, enim nec sollicitudin hendrerit, libero lorem finibus nibh, id rhoncus risus ex ut arcu. Vestibulum eget ultricies tellus. Suspendisse ut porttitor erat. Sed at nulla sit amet odio facilisis faucibus in id ante. Vestibulum at molestie arcu, sed suscipit nulla. Fusce cursus cursus felis, quis facilisis justo efficitur vitae. Cras nec velit ligula. Maecenas enim enim, vehicula quis ipsum vitae, molestie laoreet ligula. Mauris aliquam diam orci, a volutpat libero vestibulum ac. Praesent congue vehicula nunc, sit amet eleifend felis lacinia ac. Mauris interdum suscipit ligula, a facilisis neque mattis sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur blandit leo eget egestas aliquam. Cras ut arcu elit. Vivamus in erat eu sem dapibus ultricies.

Sed urna sem, maximus faucibus malesuada non, lacinia eu libero. Mauris placerat sollicitudin ullamcorper. Nam auctor tristique justo eu commodo. Morbi eu dui ultrices, lacinia felis lacinia, sollicitudin orci. Phasellus quam odio, scelerisque id pharetra ut, lacinia eu nisl. Nulla interdum quam odio, vel ultrices leo laoreet sit amet. Morbi quis felis at neque congue facilisis. Praesent varius tellus vitae scelerisque fermentum. Sed commodo risus non neque commodo dapibus. Mauris fermentum efficitur orci vel facilisis.

In convallis, arcu vel tincidunt rhoncus, urna orci interdum mauris, sed vehicula ipsum dolor ut mi. Suspendisse sit amet turpis sit amet tortor aliquet congue a ac massa. Maecenas nec nisi enim. Suspendisse pulvinar faucibus lacus, a suscipit mauris sodales eu. Phasellus vulputate dolor dolor, vel convallis ipsum accumsan vitae. Quisque sodales condimentum dolor. Cras porttitor elit vitae ligula mattis, ac tincidunt metus venenatis. Vivamus at posuere tortor. Fusce tempor nunc risus, at tincidunt metus accumsan sit amet. Nulla commodo vulputate diam in placerat. Ut accumsan mi ipsum, vel tempor dui mattis eu. Nulla facilisi.

Vivamus dignissim varius tellus, non euismod metus varius id. Integer dolor neque, dignissim et ligula nec, lobortis congue lorem. Quisque rutrum, mauris at lacinia elementum, neque sapien aliquet turpis, nec euismod odio libero a justo. Phasellus ac dolor augue. In consequat nunc mauris, at auctor lorem sodales eget. Proin quis ipsum nibh. Maecenas a est et nisi facilisis consequat. Quisque porta, tellus et bibendum pharetra, nisi felis venenatis nibh, a blandit ex mi sed nibh. In ultrices risus enim, at maximus eros tincidunt quis. Donec molestie, tellus at faucibus interdum, felis leo hendrerit leo, vitae accumsan lorem augue sed leo. Nunc luctus mi urna, id interdum eros sodales sit amet. Duis purus orci, dictum vel urna at, aliquet maximus tellus. Vestibulum porttitor, tellus eget posuere congue, tellus nibh viverra dui, quis efficitur tortor nisi vestibulum est. Nam vel dui laoreet urna suscipit faucibus a sit amet urna.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed efficitur massa, quis semper nunc. Cras elementum ante sed feugiat pellentesque. Vestibulum ut lacus malesuada, malesuada odio nec, dictum nunc. Duis hendrerit lacus vitae mauris consequat tempus. Aliquam consectetur semper neque, sit amet pulvinar elit interdum quis. Ut elementum placerat ex, sit amet tristique risus elementum quis. In facilisis augue in scelerisque facilisis. Maecenas sed ullamcorper ex, non laoreet enim. Aenean eu erat accumsan, dapibus mi in, suscipit erat. Nulla tempus nisi sit amet odio vestibulum, at auctor ligula rhoncus. Curabitur quis sapien sit amet libero semper suscipit in a ligula. Praesent vel ex eu turpis fermentum placerat sit amet sit amet turpis. Quisque egestas, quam in hendrerit consectetur, sem lectus mattis diam, iaculis semper tellus ex quis ligula.

Cras sollicitudin, enim nec sollicitudin hendrerit, libero lorem finibus nibh, id rhoncus risus ex ut arcu. Vestibulum eget ultricies tellus. Suspendisse ut porttitor erat. Sed at nulla sit amet odio facilisis faucibus in id ante. Vestibulum at molestie arcu, sed suscipit nulla. Fusce cursus cursus felis, quis facilisis justo efficitur vitae. Cras nec velit ligula. Maecenas enim enim, vehicula quis ipsum vitae, molestie laoreet ligula. Mauris aliquam diam orci, a volutpat libero vestibulum ac. Praesent congue vehicula nunc, sit amet eleifend felis lacinia ac. Mauris interdum suscipit ligula, a facilisis neque mattis sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur blandit leo eget egestas aliquam. Cras ut arcu elit. Vivamus in erat eu sem dapibus ultricies.

Sed urna sem, maximus faucibus malesuada non, lacinia eu libero. Mauris placerat sollicitudin ullamcorper. Nam auctor tristique justo eu commodo. Morbi eu dui ultrices, lacinia felis lacinia, sollicitudin orci. Phasellus quam odio, scelerisque id pharetra ut, lacinia eu nisl. Nulla interdum quam odio, vel ultrices leo laoreet sit amet. Morbi quis felis at neque congue facilisis. Praesent varius tellus vitae scelerisque fermentum. Sed commodo risus non neque commodo dapibus. Mauris fermentum efficitur orci vel facilisis.

In convallis, arcu vel tincidunt rhoncus, urna orci interdum mauris, sed vehicula ipsum dolor ut mi. Suspendisse sit amet turpis sit amet tortor aliquet congue a ac massa. Maecenas nec nisi enim. Suspendisse pulvinar faucibus lacus, a suscipit mauris sodales eu. Phasellus vulputate dolor dolor, vel convallis ipsum accumsan vitae. Quisque sodales condimentum dolor. Cras porttitor elit vitae ligula mattis, ac tincidunt metus venenatis. Vivamus at posuere tortor. Fusce tempor nunc risus, at tincidunt metus accumsan sit amet. Nulla commodo vulputate diam in placerat. Ut accumsan mi ipsum, vel tempor dui mattis eu. Nulla facilisi.

Vivamus dignissim varius tellus, non euismod metus varius id. Integer dolor neque, dignissim et ligula nec, lobortis congue lorem. Quisque rutrum, mauris at lacinia elementum, neque sapien aliquet turpis, nec euismod odio libero a justo. Phasellus ac dolor augue. In consequat nunc mauris, at auctor lorem sodales eget. Proin quis ipsum nibh. Maecenas a est et nisi facilisis consequat. Quisque porta, tellus et bibendum pharetra, nisi felis venenatis nibh, a blandit ex mi sed nibh. In ultrices risus enim, at maximus eros tincidunt quis. Donec molestie, tellus at faucibus interdum, felis leo hendrerit leo, vitae accumsan lorem augue sed leo. Nunc luctus mi urna, id interdum eros sodales sit amet. Duis purus orci, dictum vel urna at, aliquet maximus tellus. Vestibulum porttitor, tellus eget posuere congue, tellus nibh viverra dui, quis efficitur tortor nisi vestibulum est. Nam vel dui laoreet urna suscipit faucibus a sit amet urna.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed efficitur massa, quis semper nunc. Cras elementum ante sed feugiat pellentesque. Vestibulum ut lacus malesuada, malesuada odio nec, dictum nunc. Duis hendrerit lacus vitae mauris consequat tempus. Aliquam consectetur semper neque, sit amet pulvinar elit interdum quis. Ut elementum placerat ex, sit amet tristique risus elementum quis. In facilisis augue in scelerisque facilisis. Maecenas sed ullamcorper ex, non laoreet enim. Aenean eu erat accumsan, dapibus mi in, suscipit erat. Nulla tempus nisi sit amet odio vestibulum, at auctor ligula rhoncus. Curabitur quis sapien sit amet libero semper suscipit in a ligula. Praesent vel ex eu turpis fermentum placerat sit amet sit amet turpis. Quisque egestas, quam in hendrerit consectetur, sem lectus mattis diam, iaculis semper tellus ex quis ligula.

Cras sollicitudin, enim nec sollicitudin hendrerit, libero lorem finibus nibh, id rhoncus risus ex ut arcu. Vestibulum eget ultricies tellus. Suspendisse ut porttitor erat. Sed at nulla sit amet odio facilisis faucibus in id ante. Vestibulum at molestie arcu, sed suscipit nulla. Fusce cursus cursus felis, quis facilisis justo efficitur vitae. Cras nec velit ligula. Maecenas enim enim, vehicula quis ipsum vitae, molestie laoreet ligula. Mauris aliquam diam orci, a volutpat libero vestibulum ac. Praesent congue vehicula nunc, sit amet eleifend felis lacinia ac. Mauris interdum suscipit ligula, a facilisis neque mattis sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur blandit leo eget egestas aliquam. Cras ut arcu elit. Vivamus in erat eu sem dapibus ultricies.

Sed urna sem, maximus faucibus malesuada non, lacinia eu libero. Mauris placerat sollicitudin ullamcorper. Nam auctor tristique justo eu commodo. Morbi eu dui ultrices, lacinia felis lacinia, sollicitudin orci. Phasellus quam odio, scelerisque id pharetra ut, lacinia eu nisl. Nulla interdum quam odio, vel ultrices leo laoreet sit amet. Morbi quis felis at neque congue facilisis. Praesent varius tellus vitae scelerisque fermentum. Sed commodo risus non neque commodo dapibus. Mauris fermentum efficitur orci vel facilisis.

In convallis, arcu vel tincidunt rhoncus, urna orci interdum mauris, sed vehicula ipsum dolor ut mi. Suspendisse sit amet turpis sit amet tortor aliquet congue a ac massa. Maecenas nec nisi enim. Suspendisse pulvinar faucibus lacus, a suscipit mauris sodales eu. Phasellus vulputate dolor dolor, vel convallis ipsum accumsan vitae. Quisque sodales condimentum dolor. Cras porttitor elit vitae ligula mattis, ac tincidunt metus venenatis. Vivamus at posuere tortor. Fusce tempor nunc risus, at tincidunt metus accumsan sit amet. Nulla commodo vulputate diam in placerat. Ut accumsan mi ipsum, vel tempor dui mattis eu. Nulla facilisi.

Vivamus dignissim varius tellus, non euismod metus varius id. Integer dolor neque, dignissim et ligula nec, lobortis congue lorem. Quisque rutrum, mauris at lacinia elementum, neque sapien aliquet turpis, nec euismod odio libero a justo. Phasellus ac dolor augue. In consequat nunc mauris, at auctor lorem sodales eget. Proin quis ipsum nibh. Maecenas a est et nisi facilisis consequat. Quisque porta, tellus et bibendum pharetra, nisi felis venenatis nibh, a blandit ex mi sed nibh. In ultrices risus enim, at maximus eros tincidunt quis. Donec molestie, tellus at faucibus interdum, felis leo hendrerit leo, vitae accumsan lorem augue sed leo. Nunc luctus mi urna, id interdum eros sodales sit amet. Duis purus orci, dictum vel urna at, aliquet maximus tellus. Vestibulum porttitor, tellus eget posuere congue, tellus nibh viverra dui, quis efficitur tortor nisi vestibulum est. Nam vel dui laoreet urna suscipit faucibus a sit amet urna.
        </p>
    )
}